[package]
name = "riscv2llvm"
version = "0.2.0"
edition = "2021"
description = "A binary translator that lifts RISC-V to LLVM IR."
license = "MIT"

[dependencies]
clap = { version = "4.4.3", features = ["derive"] }
once_cell = "1.18.0"
rayon = "1.7.0"
regex = "1.9.5"
