[package]
name = "riscv2llvm"
version = "0.1.0"
edition = "2021"
description = "A binary translator that lifts RISC-V to LLVM IR."
license = "MIT"

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
once_cell = "1.17.1"
rayon = "1.6.1"
regex = "1.7.1"
