[package]
name = "biotite"
version = "0.2.0"
edition = "2021"
description = "A binary translator that lifts RISC-V to LLVM IR."
license = "MIT"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
once_cell = "1.19.0"
rayon = "1.8.1"
regex = "1.10.3"
