//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t f(int64_t a1);

// --------------------- Global Variables ---------------------

int64_t g1;

// ------------------------ Functions -------------------------

// Address range: 0x401110 - 0x401180
// Demangled:     float
int64_t f(int64_t a1) {
    int64_t v1 = 0x100000000 * a1;
    int64_t v2 = a1 + 0xffffffff; // 0x40111a
    g1 = v2 & 0xffffffff;
    int64_t v3 = v1; // 0x401138
    switch ((int32_t)v2) {
        case 0: {
            // 0x40113a
            v3 = v1 + 0x100000000;
            // break -> 0x40117b
            break;
        }
        case 1: {
            // 0x401148
            v3 = v1 + 0x200000000;
            // break -> 0x40117b
            break;
        }
        case 2: {
            // 0x401156
            v3 = v1 + 0x300000000;
            // break -> 0x40117b
            break;
        }
        case 3: {
            // 0x401164
            v3 = v1 + 0x400000000;
            // break -> 0x40117b
            break;
        }
        case 4: {
            // 0x401172
            v3 = v1 + 0x500000000;
            // break -> 0x40117b
            break;
        }
    }
    // 0x40117b
    return v3 / 0x100000000;
}

// Address range: 0x401180 - 0x4011c3
int main(int argc, char ** argv) {
    for (int32_t i = 0; i < 0x5f5e100; i++) {
        // 0x4011a3
        f(1);
    }
    // 0x4011bb
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (9.3.0)
// Detected functions: 2
